### ISSUE TITLE
Person content type

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/cwd_project#14]
(companion issue to [CD Demo issue #95](https://github.com/CU-CommunityApps/CD-demo/issues/95))

**Comment by alisonjo315** [comment]
@ama39  At some point, I'll need some sass/css from you from Bright Beams, my compiling skills are wayyyyy too rusty to attempt it myself (and I know that, b/c I just tried -- granted, I gave up pretty quickly, and if you have any instructions lying around, I could give it another try).

Branch to push to: https://github.com/CU-CommunityApps/cwd_project/tree/person

**Comment by ama39** [comment]
@alisonjo315 I think everything you need should already be up for you. It's a component in the [cwd_project](https://github.com/CU-CommunityApps/cwd_project) theme, so you should just need to update that theme on your multidev.
