### ISSUE TITLE
project.js gives error

### ISSUE THREAD

**Issue by philwilliammee** [CU-CommunityApps/cwd_project#2]
project .js line 31
Uncaught SyntaxError: Unexpected token }

**Comment by woodseowl** [comment]
I'm guessing this is the same as was fixed here in an implemented version of this new theme...

https://github.com/CU-CommunityApps/CD-SCL/pull/25/commits/60a2f58de9247dc9d53663bdfb8a79cf37799264

**Comment by alisonjo315** [comment]
Looking, thanks!

**Comment by alisonjo315** [comment]
(closing the loop, so to speak) 

Fixed by Phil back on 2019-09-11, as implied by the PR reference further up in this thread ⭐️
