### ISSUE TITLE
CKEditor template preview thumbnail images are missing

### ISSUE THREAD

**Issue by philwilliammee** [CU-CommunityApps/cwd_project#5]
See Phil's explanation (and screenshots!) in [his comment below](https://github.com/CU-CommunityApps/cwd_project/issues/5#issuecomment-586329461).

ckeditor_templates.js line 10 references a non-existent folder of template "preview"/thumbnail images:
https://github.com/CU-CommunityApps/cwd_project/blob/022ad7ae616fac6918a973436b7db9071c4addde/templates/ckeditor_templates.js#L10

(This reference is NOT for placeholder images used within actual WYSIWYG templates!)

----

**Option 1:** Add preview/thumbnail images of each template option in the referenced sub-folder (or some other folder).

**Option 2:** Remove (or comment-out) this line.

**Comment by alisonjo315** [comment]
Good catch!

Ideally, we'd use media embeds for these, not images -- I think @woodseowl said (a few months ago) he might've been working on how to do media embeds in wysiwyg templates, idk if that worked out?

**Comment by woodseowl** [comment]
I think that was on the FCS project (fcs-main on pantheon) and what I found was a commit where I was matching styles to the CSS framework:

"Updating CKEditor styles to match styleguide (node these edits need to go back to cwd_base & CD Demo)"
Oct 23, 2019 at 3:58 PM - 9b31d4bb3

Which I don't think I have done.

**Comment by alisonjo315** [comment]
Ah, ok, I thought I remembered you saying you might be doing something like that for SCL or Migrations... But either way, if you haven't done it, you haven't done it :D thanks!

**Comment by ama39** [comment]
May I get a little more context on this? Which images are missing? Do you mean placeholder photos (like the Big red Bear) in design patterns that can be dropped in via the Templates button? If so, those photos where previously just direct references to photos housed in the base theme. They could then be double-clicked to replace them via whatever media system was in place in Drupal. Is that no longer working?

**Comment by alisonjo315** [comment]
I think all WYSIWYG templates that use images should be removed, and then have a task to add new templates that have placeholder images via media objects (or something).  I think it's important to remove the ones that embed straight images...

...to prevent CE folks don't put "legacy" images in there;
...also because if the images are there, there's no way to add more "images" like the placeholders in that space;
...also because we need the template'd markup to work with image media objects, not just image objects.

**Comment by philwilliammee** [comment]
yeah I used this and thought it was odd that a  imagesPath is referenced, I dont think the path exists because there is no images folder in the starter project. also there are commented out images in the ckeditor template. If we dont support those images then the commented out lines can be removed
